import {topics,projects} from './curriculum';
import {stats,type State,type Skill} from './model';
export const mentorQuestions=['O que devo estudar hoje?','Qual meu próximo tópico em Java?','Estou pronto para POO?','Estou pronto para Spring Boot?','Me dê um exercício adequado ao meu nível.','Qual parte do inglês devo praticar?','Estou negligenciando alguma habilidade?','Estou pronto para procurar estágio?'];
export function recommend(state:State,track='java'){return topics.find(t=>t.track===track&&state.topics[t.id]?.status==='studying')??topics.find(t=>t.track===track&&state.topics[t.id]?.status!=='done');}
export function mentorAnswer(question:string,state:State){
 const q=question.toLowerCase();const next=recommend(state);const s=stats(state,topics);
 const missing=(stages:string[])=>topics.filter(t=>t.track==='java'&&stages.includes(t.stage)&&state.topics[t.id]?.status!=='done');
 if(q.includes('poo')||q.includes('spring')){const spring=q.includes('spring');const pending=missing(spring?['Fundamentos','Java básico & Git','POO & Testes','Banco de Dados & SQL']:['Fundamentos','Java básico & Git']);return pending.length?`Ainda há ${pending.length} tópicos prévios sem conclusão registrada. Comece por ${pending.slice(0,3).map(t=>t.title).join(', ')}. Se você já domina esses conteúdos, revise e atualize os registros. O PDF aponta POO em consolidação, mas isso não confirma automaticamente os pré-requisitos.`:`Os pré-requisitos do roteiro para ${spring?'Spring Boot':'POO'} estão registrados como concluídos. Antes de avançar, faça um pequeno projeto sem tutorial e explique suas decisões. A checklist indica cobertura; a demonstração prática confirma domínio.`;}
 if(q.includes('ingl')||q.includes('habilidade')||q.includes('neglig')){const skills:Skill[]=['Listening','Speaking','Reading','Writing'];const ranked=skills.map(skill=>({skill,minutes:state.sessions.filter(x=>x.track==='english'&&x.skill===skill).reduce((n,x)=>n+x.minutes,0)})).sort((a,b)=>a.minutes-b.minutes);return `A habilidade com menos tempo registrado é ${ranked[0].skill}: ${ranked[0].minutes} min. ${state.sessions.some(x=>x.track==='english')?'Compare esse dado com sua dificuldade percebida.':'Ainda não há sessões de inglês; isso não permite inferir seu nível real.'} Sugestão: ${ranked[0].skill==='Listening'?'ouça um áudio curto e anote a ideia principal':ranked[0].skill==='Speaking'?'faça shadowing e grave sua voz':ranked[0].skill==='Reading'?'leia um texto adequado à etapa e registre cinco expressões':'escreva cinco frases próprias e revise'}. Próximo conteúdo: ${recommend(state,'english')?.title??'revisão dos entregáveis avançados'}.`;}
 if(q.includes('estágio')||q.includes('emprego')){const pending=missing(['Fundamentos','Java básico & Git','POO & Testes','Banco de Dados & SQL','Spring Boot','Portfólio & Carreira']);const completed=projects.filter(p=>p.track==='java'&&state.projects[p.id]?.status==='done');return `Você registrou ${completed.length} projetos Java concluídos e tem ${pending.length} tópicos Java pendentes. ${pending.length?`Priorize ${pending.slice(0,3).map(t=>t.title).join(', ')}.`:'A cobertura do plano está concluída.'} Para avaliar candidaturas, demonstre uma API com banco, testes, README e explicação das decisões, e pratique entrevistas. Estes registros não garantem contratação; você pode comparar seu portfólio com os requisitos das vagas e começar candidaturas durante os estudos.`;}
 if(q.includes('exercício'))return next?`Para ${next.title}: ${next.exercises.find(x=>x.startsWith('Microprática'))?.replace('Microprática complementar: ','')??next.exercises[0]??`Crie um exemplo que demonstre ${next.content[0]}.`} Faça sem copiar, teste uma falha e anote o que precisou pesquisar.`:'Escolha um projeto concluído e adicione uma funcionalidade com testes.';
 if(q.includes('próximo')||q.includes('hoje')){const difficult=state.sessions.find(x=>x.difficulty==='Difícil');return next?`Seu próximo passo registrado em Java é ${next.title}, na etapa ${next.stage}. Reserve 25 minutos: entenda um exemplo, pratique e registre a sessão. ${difficult?`Revise também a dificuldade anotada em ${topics.find(t=>t.id===difficult.topic)?.title??difficult.activity}.`:''} Você tem ${s.minutes} minutos e ${s.done} tópicos concluídos registrados.`:'A trilha Java está concluída nos registros. Revise um projeto, pratique uma entrevista e mantenha o inglês ativo.';}
 return 'Nesta primeira versão, uso regras e seus registros reais. Posso orientar o próximo tópico, pré-requisitos de POO e Spring Boot, exercícios, equilíbrio do inglês e preparação para estágio. Escolha uma das perguntas sugeridas para uma análise objetiva.';
}
